#!/bin/bash
#
# setup.sh - Production setup for Pseudoscopic
#
# This script prepares the environment, installs dependencies,
# configures the driver, and builds the project.
#
# Usage: sudo ./setup.sh
#

set -e

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Pseudoscopic Production Setup ===${NC}"

# Check for root
if [ "$EUID" -ne 0 ]; then 
  echo -e "${RED}Please run as root (sudo ./setup.sh)${NC}"
  exit 1
fi

# 1. Install Dependencies
echo -e "\n${YELLOW}[1/5] Installing system dependencies...${NC}"
apt-get update
apt-get install -y \
    build-essential \
    linux-headers-$(uname -r) \
    dkms \
    git \
    bc \
    bison \
    flex \
    libelf-dev \
    libssl-dev

# 2. Configure Driver options
echo -e "\n${YELLOW}[2/5] Configuring driver options...${NC}"
# Default to second GPU (device_idx=1) as requested
# Set mode=ramdisk for examples compatibility
cat > /etc/modprobe.d/pseudoscopic.conf << EOF
# Pseudoscopic Configuration
# Generated by setup.sh

# Default to second GPU (skip primary display)
# device_idx=1 targets the second NVIDIA device found by the kernel.
options pseudoscopic device_idx=1 mode=ramdisk
EOF
echo "Created /etc/modprobe.d/pseudoscopic.conf"

# 3. Build Kernel Module
echo -e "\n${YELLOW}[3/5] Building kernel module...${NC}"
# Uninstall if already loaded
if lsmod | grep -q "pseudoscopic"; then
    echo "Unloading existing module..."
    rmmod pseudoscopic || true
fi

# Clean and build (using root Makefile)
make clean
make

# Install/Load
echo "Installing module..."
make install
depmod -a

# Attempt to load
echo "Loading module..."
if modprobe pseudoscopic; then
    echo -e "${GREEN}Module loaded successfully!${NC}"
    dmesg | tail -n 5 | grep "pseudoscopic"
else
    echo -e "${RED}Error: Module load failed. Pseudoscopic technology not available.${NC}"
    echo "Check dmesg for details."
    exit 1
fi

# 4. Build Userspace Library & Examples
echo -e "\n${YELLOW}[4/5] Building Near-Memory Library & Examples...${NC}"
cd contrib/nearmem

# Check CUDA
if ! command -v nvcc &> /dev/null; then
    echo -e "${YELLOW}Warning: nvcc not found. Building in CPU-only mode (demos will be slow).${NC}"
    echo "Please install CUDA Toolkit for full performance."
else
    echo "CUDA found: $(which nvcc)"
fi

make clean
make

# Install library
make install
ldconfig

echo -e "\n${YELLOW}[5/5] Checking Environment...${NC}"
# Verify device nodes (if loaded)
if ls /dev/psdisk* 1> /dev/null 2>&1; then
    echo -e "Device nodes found: ${GREEN}$(ls /dev/psdisk*)${NC}"
    
    # Symlink setup (optional, but helpful)
    # If /dev/psdisk1 exists but not 0, create a symlink?
    # Our updated examples use auto-detection, so this is less critical,
    # but good for user convenience.
    DEVICE=$(ls /dev/psdisk* | head -n 1)
    if [ ! -e "/dev/pseudoscopic" ]; then
        ln -sf $DEVICE /dev/pseudoscopic
        echo "Created /dev/pseudoscopic -> $DEVICE"
    fi
else
    echo -e "${RED}Error: No Pseudoscopic device nodes found (/dev/psdisk*).${NC}"
    echo "Driver loaded but no compatible GPU claimed."
    exit 1
fi

echo -e "\n${GREEN}=== Setup Complete! ===${NC}"
echo "You can now run the demos in contrib/nearmem/examples/"
echo "Example: ./contrib/nearmem/gpucpu_demo"
